server.port=${PORT:8081}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/DBJava_SpringBoot_DEV?serverTimezone=UTC&useSSL=false
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/DBJava_SpringBoot_DEV?serverTimezone=UTC&useSSL=false
spring.datasource.username=dev
spring.datasource.password=Dev!2025
api.auth.login.privateKey=http://localhost:8082/api/security/keys/getPrivateKey
api.auth.login.passKey=http://localhost:8082/api/security/passkeys/getPassKeys