spring.application.name=key_service
server.port=${PORT:8081}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:docker_rj_local_2026}

# --- Configuración de tu Lógica de Microservicios ---
# Aquí puedes definir nombres de 'tablas' (claves de hashes) para Redis
#app.redis.key-public-current=public_key:current
#app.redis.key-public-previous=public_key:previous

# Tiempo de expiración opcional (si quieres que las llaves roten)
# 0 significa que no expira
#app.security.key-expiration-days=0
